import type {
  CategoryItem,
  PlanCard,
  HeroEvent,
  DealItem,
  HeritageTour,
  NavigationItem,
} from './types'
import heroConcertStage from '@/assets/images/hero-concert-stage.jpg'

export const banners = [
  '/banner.png',
  heroConcertStage,
  '/banner2.png',
  'https://images.unsplash.com/photo-1540039155732-6761b54cb432?q=80&w=2000&auto=format&fit=crop',
]

export const navigationItems: NavigationItem[] = [
  { label: 'Explore Events', href: '/events', isActive: true },
  { label: 'Categories', href: '/categories' },
  { label: 'Dining & Deals', href: '/deals' },
  { label: 'Heritage', href: '/heritage' },
  { label: 'Sports Mania', href: '/sports' },
  { label: 'My Bookings', href: '/bookings' },
]

export const categories: CategoryItem[] = [
  { id: '1', label: 'Music', icon: '🎵', color: '#dc2626', href: '/category/music' },
  { id: '2', label: 'Dining', icon: '🍽️', color: '#f59e0b', href: '/category/dining' },
  { id: '3', label: 'Art & Visuals', icon: '🎨', color: '#8b5cf6', href: '/category/art' },
  { id: '4', label: 'Nightlife', icon: '🌙', color: '#ec4899', href: '/category/nightlife' },
  { id: '5', label: 'Heritage', icon: '🏛️', color: '#10b981', href: '/category/heritage' },
  { id: '6', label: 'Sports', icon: '⚽', color: '#3b82f6', href: '/category/sports' },
  { id: '7', label: 'Startup', icon: '🚀', color: '#06b6d4', href: '/category/startup' },
  { id: '8', label: 'Screenings', icon: '🎬', color: '#f97316', href: '/category/screenings' },
]

export const planCards: PlanCard[] = [
  {
    id: 'today',
    label: 'SAME DAY PASSES',
    title: 'PLANS FOR TODAY',
    description: '15 live shows happening right now',
    icon: '⚡',
    accentColor: '#dc2626',
    href: '/events?when=today',
  },
  {
    id: 'tomorrow',
    label: 'ADVANCE BOOKINGS',
    title: 'PLANS FOR TOMORROW',
    description: 'Pre-reserve hot tables & seats',
    icon: '📅',
    accentColor: '#06b6d4',
    href: '/events?when=tomorrow',
  },
  {
    id: 'weekend',
    label: 'FRI - SUN SPECIALS',
    title: 'PLANS FOR WEEKEND',
    description: 'Festivals, clubs & curated walks',
    icon: '🎉',
    accentColor: '#3b82f6',
    href: '/events?when=weekend',
  },
]

export const trendingEvents: HeroEvent[] = [
  {
    id: '1',
    title: 'Neon Beats Party',
    description: 'Electrotronic indie featuring renowned indie artists with immersive visual mapping and signature cocktails',
    date: 'Sat, 27 May',
    time: '20:30',
    venue: 'The Grounds',
    location: 'Park Street',
    price: 1599,
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&h=400&fit=crop',
    badge: 'LIVE MUSIC NIGHT',
    badgeColor: 'red',
    category: 'Music',
    isLive: true,
  },
  {
    id: '2',
    title: 'Live Karaoke & Unplugged',
    description: 'Grab the stage or chill with the city\'s finest acoustic vocalists. Complimentary starter with every entry pass.',
    date: 'Wed, 27 May',
    time: '20:30',
    venue: 'Acoustic Lounge',
    location: 'Salt Lake',
    price: 1299,
    image: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=600&h=400&fit=crop',
    category: 'Music',
  },
  {
    id: '3',
    title: 'After Dark Electronic Session',
    description: 'High energy deep house & lo-fi rhythms overlooking the historic skyline. Premium bar wellstock.',
    date: 'Sat, 27 May',
    time: '21:00',
    venue: 'Rooftop Club',
    location: 'Park Street',
    price: 1899,
    image: 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=600&h=400&fit=crop',
    category: 'Nightlife',
  },
  {
    id: '4',
    title: 'Sunset Jazz Evening',
    description: 'Smooth jazz performances with craft cocktails and stunning city views.',
    date: 'Fri, 26 May',
    time: '18:00',
    venue: 'Sky Lounge',
    location: 'Ballygunge',
    price: 999,
    image: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=600&h=400&fit=crop',
    category: 'Music',
  },
]

export const spotlightEvents: HeroEvent[] = [
  {
    id: 's1',
    title: 'Bollywood Music Party',
    description: 'Live Music',
    date: '',
    time: '20:30',
    venue: 'Garrets',
    location: '',
    price: 699,
    image: 'https://images.unsplash.com/photo-1504509546545-e000b4a62425?w=600&h=400&fit=crop',
    badge: 'BOLLYWOOD NIGHTS',
    badgeColor: 'red',
    category: 'Music',
  },
  {
    id: 's2',
    title: 'Saturday Fun Party - Arthur Senna',
    description: 'Live Music',
    date: '',
    time: '20:00',
    venue: 'Soho London',
    location: '',
    price: 599,
    image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&h=400&fit=crop',
    badge: 'INTERNATIONAL HEADLINERS',
    badgeColor: 'amber',
    category: 'Music',
  },
  {
    id: 's3',
    title: 'History Photo Effect Showcase',
    description: 'Screening',
    date: '',
    time: '20:30',
    venue: 'Tagore',
    location: '',
    price: 899,
    image: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=600&h=400&fit=crop',
    badge: 'LOCAL MOTION PICTURES',
    badgeColor: 'emerald',
    category: 'Screenings',
  },
]

export const hotDeals: DealItem[] = [
  {
    id: 'd1',
    title: 'JW Marriott Hotel Kolkata',
    subtitle: 'Bengali Cuisine • 4.8 ★ • Premium Dining',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&h=400&fit=crop',
    discount: 'Flat 20% on all Buffets + Flat 10% off',
    price: '2999',
    originalPrice: '3999',
    category: 'Hotel',
    href: '/deals/jw-marriott',
  },
  {
    id: 'd2',
    title: 'Hyatt Waterside Cafe',
    subtitle: 'Continental • 4.5 ★ • Café & Lounge',
    image: 'https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=600&h=400&fit=crop',
    discount: 'Flat 25% Off for Buffet + Free Dessert',
    price: '1299',
    originalPrice: '1899',
    category: 'Cafe',
    href: '/deals/hyatt',
  },
  {
    id: 'd3',
    title: 'The Westin Seasonal Tastes',
    subtitle: 'Asian, North Indian • 4.6 ★ • Restaurant',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop',
    discount: 'Flat 15% off a la carte + Flat 10% off',
    price: '1999',
    originalPrice: '2499',
    category: 'Restaurant',
    href: '/deals/westin',
  },
  {
    id: 'd4',
    title: 'Aqua Java Cafe & Shah',
    subtitle: 'Italian, Continental • 4.4 ★ • Café & Lounge',
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&h=400&fit=crop',
    discount: 'Flat 20% Off on Breakfast + Flat 15% Off',
    price: '899',
    originalPrice: '1299',
    category: 'Cafe',
    href: '/deals/aqua-java',
  },
]

export const heritageTours: HeritageTour[] = [
  {
    id: 'h1',
    title: 'Victoria Memorial',
    description: 'Guided tour through marble marvel & royal gardens',
    image: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?w=600&h=400&fit=crop',
    duration: '2-3 Hours',
    price: '₹1,500',
    location: 'Outdoors • Venue • 16.4 KM',
    href: '/heritage/victoria-memorial',
  },
  {
    id: 'h2',
    title: 'Howrah Bridge & River Ferry',
    description: 'Heritage walk & sunset ferry ride',
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=600&h=400&fit=crop',
    duration: '3-4 Hours',
    price: '₹850',
    location: 'Outdoors • Venue • Ghats Trail',
    href: '/heritage/howrah-bridge',
  },
  {
    id: 'h3',
    title: 'Kumortuli Clay & Artisan Walk',
    description: 'Guided tour of North Kolkata',
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600&h=400&fit=crop',
    duration: '2 Hours',
    price: '₹450',
    location: 'Guided Tour • North Kolkata',
    href: '/heritage/kumortuli',
  },
]
